version: "3"
services:
  web:
    build: .
    ports:
      - "80:80"
    restart: always
    env_file:
      - .flaskenv
    volumes:
      - ./flask.sqlite:/mlh_portfolio_aws/flask.sqlite
    volumes:
      - .:/mlh_portfolio_aws
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .flaskenv