version: "3"
services:
  web:
    build: .
    restart: always
    env_file:
      - .flaskenv
    volumes:
      - .:/mlh_portfolio_aws
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .flaskenv

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - web
  
  volumes:
    nginx_secrets: